#!/bin/bash

set -e

if [[ $# != 1 ]]; then
    echo "Please speciify a file to publish for me."
    exit 1;
fi

POST=$1
TIMEZONE=$(date -j '+%z')

if [[ ! -e $POST ]]; then
    echo "File '$POST' not found."
    exit 1;
fi

CUR_DATE=$(date -j '+%Y-%m-%d')
CUR_TIME=$(date -j '+%T')

PUBLISHED_POST="_posts/$CUR_DATE-$(basename $POST)"
echo $PUBLISHED_POST

cat $POST | sed -e "/title:.*/a \\
    date: $CUR_DATE $CUR_TIME $TIMEZONE" > $PUBLISHED_POST

rm "_drafts/$(basename $POST)"
